---
title: "Data_Analysis_JRME"
author: "Sebastian Robledo"
date: "6/25/2021"
output: html_document
---

# Creating the environment 

```{r}
library(lavaan)
library(here)
library(tidyverse)
library(semTools)
library(stargazer)
```

# Getting data 

```{r}
data_jrme <- 
  read.csv(here("data",
                "jrme_data_all.csv")) |> 
  mutate(Net_Str = constraint_sc)
```

# Try 2

http://www.koreascience.or.kr/article/JAKO201919059190001.view

```{r}
data_jrme_mod <- 
  semTools::indProd(df_dummy,
                    var1 = c("NET_Q1", "NET_Q2", "NET_Q3", "NET_Q4"),
                    var2 = c("ME_Q1", "ME_Q2", "ME_Q3", "ME_Q4"),
                    match = FALSE,
                    meanC = TRUE,
                    residualC = FALSE,
                    doubleMC = TRUE)
```

New variables

```{r}
data_jrme_mod |> 
  select(57:72) |> 
  names()
```

Model 

```{r}
networking_model_mod <- 
  "# measurement model
   networking_jrme =~ NET_Q1 + NET_Q2 + NET_Q3 + NET_Q4
   effectuation =~ ME_Q1 + ME_Q2 + ME_Q3 + ME_Q4
   net_structure =~ constraint_raw
   # interaction term
   networkingeffectuation =~ NET_Q1.ME_Q1 + NET_Q1.ME_Q2 + NET_Q1.ME_Q3 + NET_Q1.ME_Q4 +
                             NET_Q2.ME_Q1 + NET_Q2.ME_Q2 + NET_Q2.ME_Q3 + NET_Q2.ME_Q4 +
                             NET_Q3.ME_Q1 + NET_Q3.ME_Q2 + NET_Q3.ME_Q3 + NET_Q3.ME_Q4 +
                             NET_Q4.ME_Q1 + NET_Q4.ME_Q2 + NET_Q4.ME_Q3 + NET_Q4.ME_Q4
   # regressions
   net_structure ~ networking_jrme + effectuation + networkingeffectuation
   # residual correlations"
```

Model fit 

```{r}
networking_fit_mod <- 
  sem(model = networking_model_mod, 
      data = data_jrme_mod)
```


```{r}
summary(networking_fit_mod, standardized = TRUE)
```


```{r}
parameterestimates(networking_fit_mod, standardized = TRUE)
```
```{r}
parameterestimates(networking_fit_mod, standardized = TRUE) |> 
  filter(op == "~") |> 
  mutate(stars = ifelse(pvalue < 0.001, "***",
                        ifelse(pvalue < 0.01, "**",
                               ifelse(pvalue < 0.05, "*", "")))) |> 
  select(LHS = lhs, RHS = rhs, Coefficient = est, 
         Z = z, "p-value" = pvalue, Sig. = stars) |> 
  stargazer(type = "text", title = "Regression Coefficients", 
            summary = FALSE, digits = 3, 
            digits.extra = 0, rownames = FALSE)
```


# Try 1

## Moderating effect

Creating the interaction term between networking and effectuation

```{r}
data_jrme_modet <- 
  data_jrme |> 
  mutate(networking_x_effectuation = networking * modelo_efectual)
```

Parameters

```{r}
moderation_model <- "
  # regressions
  Net_Str ~ b1*networking
  Net_Str ~ b2*modelo_efectual
  Net_Str ~ b3*networking_x_effectuation
  
  modelo_efectual ~ modelo_efectual.mean*1
  
  modelo_efectual ~~ modelo_efectual.var*modelo_efectual
  
  SD.below := b1 + b3*(modelo_efectual.mean - sqrt(modelo_efectual))
  mean := b1 + b3*(modelo_efectual)
  SD.above := b1 + b3*(modelo_efectual.mean + sqrt(modelo_efectual))
  "


EffecModel_jrme <- "
                    
                    networking ~ modelo_efectual
                    Net_Str ~ networking
                    "
```


```{r}
sem1 <- 
  cfa(EffecModel_jrme, data = data_jrme_modet)
```

```{r}
summary(sem1, fit.measures=TRUE, standardized=T,rsquare=T)
```

